// scripts/generate-locales.js
const fs = require('fs');
const path = require('path');

// Configuration
const localesDir = path.join(__dirname, '../src/locales');
const destDir = path.join(__dirname, '../src/js');
const destFile = path.join(destDir, 'locales.gen.js');

// Ensure destination directory exists
if (!fs.existsSync(destDir)) {
    fs.mkdirSync(destDir, { recursive: true });
}

try {
    console.log('Scanning for locales...');

    // Read all JSON files from the locales directory
    const files = fs.readdirSync(localesDir);
    const locales = files
        .filter(file => file.endsWith('.json'))
        .map(file => path.basename(file, '.json'))
        .sort();

    console.log(`Found locales: ${locales.join(', ')}`);

    // Generate the content
    const content = `// Auto-generated by scripts/generate-locales.js
// Do not edit this file directly.

/**
 * List of supported BCP 47 locale codes.
 * Generated from filenames in src/locales/*.json
 */
export const SUPPORTED_LOCALES = ${JSON.stringify(locales, null, 4)};
`;

    // Write the file
    fs.writeFileSync(destFile, content);
    console.log(`✅ Generated ${destFile}`);

} catch (error) {
    console.error('❌ Error generating locales:', error);
    process.exit(1);
}
