const fs = require('fs');
const path = require('path');
const themeConfig = require('./theme-config');

// Paths
const stylesIndex = path.join(__dirname, '../src/styles/index.css');
const themesDir = path.join(__dirname, '../src/styles/themes');
const generatedConfigPath = path.join(__dirname, '../src/js/');
const generatedConfigFile = path.join(generatedConfigPath, 'themeConfig.gen.js');

/**
 * Helper to replace content between markers (Keep this for the CSS file, that's fine)
 */
function replaceBlock(content, blockName, newContent) {
    let startTag = blockName;
    if (!blockName.startsWith('//') && !blockName.startsWith('/*')) {
        startTag = `/* ${blockName} */`;
    }
    let endTag = startTag.replace('START', 'END');

    // Escape for regex
    const safeStart = startTag.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
    const safeEnd = endTag.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');

    const regex = new RegExp(`${safeStart}[\\s\\S]*?${safeEnd}`, 'g');

    if (!regex.test(content)) {
        console.warn(`⚠️ Marker ${startTag} not found in CSS.`);
        return content;
    }

    return content.replace(regex, `${startTag}\n${newContent}\n${endTag}`);
}

function main() {
    console.log('🎨 Updating Themes...');

    // Ensure generated directory exists
    if (!fs.existsSync(generatedConfigPath)){
        fs.mkdirSync(generatedConfigPath, { recursive: true });
    }

    // 1. Verify CSS files exist
    const cssFiles = fs.readdirSync(themesDir);
    const validThemes = [];
    const themeDataForJs = {};

    Object.keys(themeConfig).forEach(key => {
        if (cssFiles.includes(`${key}.css`)) {
            validThemes.push(key);
            themeDataForJs[key] = themeConfig[key];
        } else {
            console.warn(`⚠️ Warning: Config has theme "${key}" but "${key}.css" not found. Skipping.`);
        }
    });

    // 2. Update styles/index.css (We still do this via Regex/Block replacement because CSS imports are weird)
    const cssImports = validThemes
        .map(theme => `@import 'themes/${theme}.css';`)
        .join('\n');

    let cssContent = fs.readFileSync(stylesIndex, 'utf8');
    cssContent = replaceBlock(cssContent, 'START-AUTOGEN-THEMES', cssImports);
    fs.writeFileSync(stylesIndex, cssContent);
    console.log('✅ Updated styles/index.css');

    // 3. Generate the JS Config File (The new clean way)
    const fileContent = `// Auto-generated by scripts/update-themes.js
// Do not edit this file directly.

export const AVAILABLE_THEMES = ${JSON.stringify(validThemes, null, 4)};

export const THEME_CONFIG = ${JSON.stringify(themeDataForJs, null, 4)};
`;

    fs.writeFileSync(generatedConfigFile, fileContent);
    console.log(`✅ Generated ${generatedConfigFile}`);

    console.log('🚀 Theme update complete!');
}

main();